#!/usr/bin/env bash
# One GPU worker for the a0 + a1 arm of the 100-seed campaign.
#
# Claims seeds from queue/a01_seeds.txt until the queue is empty.  The claim is
# `mkdir queue/a01_claim_<seed>` -- atomic on POSIX, so both rita GPUs share one
# queue with no lock server and no static split that would strand a free GPU.
# This is the same pattern analysis_2's joint_worker.sh already uses.
#
# Per seed: analysis_0's four K=1 scans (two AGN ~40 s, two GAL ~790 s) then
# analysis_1's two matched-host controls (AGN ~38 s, GAL ~765 s).  ~0.56 GPU-h on
# an A100-40; rita's A100-80s are the faster card (seeds 103/105 measured 2.90 vs
# 3.93 s/cell), so expect ~0.45.
#
# A seed is skipped unless generation has left every input the scans open, so a
# worker can start before generation has finished and simply pick up what is ready.
set -uo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=/hildafs/projects/phy230014p/magana/gws-agn/working
A0=$ROOT/analyses/analysis_0_pure_tracer_H0
A1=$ROOT/analyses/analysis_1_complete_catalog_H0
DATA=$ROOT/data
Q=$HERE/queue
ME="${SLURM_JOB_ID:-$$}.${SLURM_ARRAY_TASK_ID:-0}"

export XLA_PYTHON_CLIENT_PREALLOCATE=false
# the campaign pin -- analyses 0-2 of record ran on 2b86a2d, not on the main
# checkout (now b324bed) nor on the selection redo's 0c5b3db.  See pin.sh.
. "$HERE/pin.sh"
ds_pin_guard || exit 1
export OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 MKL_NUM_THREADS=4
export SEL_BATCH=${SEL_BATCH:-50000} PE_BLOCK=${PE_BLOCK:-25}
export KDE_W=${KDE_W:-4096} LOG10N0=${LOG10N0:--24}
PY=/hildafs/home/magana/tmp_ondemand_hildafs_phy230014p_symlink/magana/.conda/envs/jax/bin
export PATH="$PY:$PATH"

echo "[a01 $ME] $(hostname) start $(date -u +%FT%TZ)"
echo "[a01 $ME] darksirens @ $(git -C "$DARKSIRENS_SRC" rev-parse --short HEAD 2>/dev/null)"
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || true

# A seed is only scannable if its dataset was BUILT on the pinned SHA.  META.json
# records it (stages.events.darksirens_sha), so this catches a seed that predates the
# guard or was generated by hand against the main checkout.
seed_sha_ok () {
  local D=$1
  python - "$D/META.json" "$DS_PIN_SHA" <<'PYEOF'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(1)
want = sys.argv[2]
got = d.get("darksirens_sha") or d.get("stages", {}).get("events", {}).get("darksirens_sha")
sys.exit(0 if got == want else 1)
PYEOF
}

ready () {  # every input the two analyses open must be on disk
  local S=$1 D=$DATA/seed$1
  for f in surveys/survey_gal_complete_ns32.h5 surveys/survey_agn_complete_ns32.h5 \
           events/events.h5 events/events_puregal.h5 events/events_pureagn.h5 \
           injections/injections_targeted.h5; do
    [ -s "$D/$f" ] || return 1
  done
  seed_sha_ok "$D" || { echo "[a01] seed $S built on the WRONG darksirens SHA; refusing" >&2; return 1; }
  return 0
}

PASSES=0
while true; do
  CLAIM=""
  while read -r S; do
    [ -z "$S" ] && continue
    # already complete?  a0 writes 4 grids, a1 writes 2.
    n0=$(ls "$A0"/results/h0_pure{gal,agn}_{targeted,popuni}_s${S}.h5 2>/dev/null | wc -l)
    n1=$(ls "$A1"/results/ctrl_{gal,agn}_matched_s${S}.h5 2>/dev/null | wc -l)
    [ "$n0" -eq 4 ] && [ "$n1" -eq 2 ] && continue
    ready "$S" || continue
    if mkdir "$Q/a01_claim_$S" 2>/dev/null; then CLAIM=$S; break; fi
  done < "$Q/a01_seeds.txt"

  if [ -z "$CLAIM" ]; then
    # nothing claimable: either the queue is drained or generation is still catching
    # up.  Distinguish the two so a worker does not exit while seeds are still coming.
    PENDING=$(while read -r S; do [ -z "$S" ] && continue
                n0=$(ls "$A0"/results/h0_pure{gal,agn}_{targeted,popuni}_s${S}.h5 2>/dev/null | wc -l)
                [ "$n0" -eq 4 ] || echo "$S"
              done < "$Q/a01_seeds.txt" | wc -l)
    if [ "$PENDING" -eq 0 ] || [ -f "$Q/a01_STOP" ]; then
      echo "[a01 $ME] queue drained ($PASSES seeds done here); exiting"; break
    fi
    echo "[a01 $ME] $(date -u +%T) nothing ready ($PENDING seeds still pending generation); sleeping 120s"
    sleep 120; continue
  fi

  S=$CLAIM
  echo "$ME $(date -u +%FT%TZ)" > "$Q/a01_claim_$S/owner"
  echo "[a01 $ME] $(date -u +%T) -> seed $S"
  T0=$(date +%s); OK=1

  ( cd "$A0" && ./scripts/run_scans.sh "$S" ) >> "$HERE/logs/a01_s${S}.log" 2>&1 || OK=0
  if [ "$OK" = 1 ]; then
    ( cd "$A1" && ./scripts/run_seed_controls.sh "$S" ) >> "$HERE/logs/a01_s${S}.log" 2>&1 || OK=0
  fi

  DT=$(( $(date +%s) - T0 ))
  if [ "$OK" = 1 ]; then
    touch "$Q/a01_claim_$S/done"; PASSES=$((PASSES+1))
    echo "[a01 $ME] seed $S OK in ${DT}s"
  else
    touch "$Q/a01_claim_$S/failed"
    echo "[a01 $ME] seed $S FAILED after ${DT}s (see logs/a01_s${S}.log)"
  fi
done
echo "[a01 $ME] exit $(date -u +%FT%TZ)"
