#!/usr/bin/env bash
# One GPU worker for analysis_2's joint (H0, f_AGN) grids, 100-seed campaign.
#
# Same claim protocol as analysis_2/scripts/joint_worker.sh -- `mkdir claim_<i>` is
# atomic, a chunk whose output .h5 already exists is skipped, so a killed worker
# leaves a queue that is simply re-runnable after `rm -rf queue100/claim_*`.  It is
# kept in its own queue directory so it cannot disturb the 48 claims of the original
# six-grid campaign.
#
# THIS MATTERS FOR THIS CAMPAIGN: the joint grid is 8241 K=2 evaluations per seed and
# the local H100 cannot finish 45 of them inside one 7-day allocation.  Chunking is
# what makes that survivable -- successive allocations pick up exactly where the last
# one stopped, with no bookkeeping.
set -uo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
A2=/hildafs/projects/phy230014p/magana/gws-agn/working/analyses/analysis_2_complete_catalog_H0_fagn
DATA=/hildafs/projects/phy230014p/magana/gws-agn/working/data
Q=$HERE/queue100
ME="${SLURM_JOB_ID:-$$}.${SLURM_ARRAY_TASK_ID:-0}"

export XLA_PYTHON_CLIENT_PREALLOCATE=false
# the campaign pin -- analyses 0-2 of record ran on 2b86a2d, not on the main
# checkout (now b324bed) nor on the selection redo's 0c5b3db.  See pin.sh.
. "$HERE/pin.sh"
ds_pin_guard || exit 1
export OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 MKL_NUM_THREADS=4
PY=/hildafs/home/magana/tmp_ondemand_hildafs_phy230014p_symlink/magana/.conda/envs/jax/bin
export PATH="$PY:$PATH"

N=$(wc -l < "$Q/tasks.txt")
echo "[a2 $ME] $(hostname) start $(date -u +%FT%TZ); $N chunks queued"
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || true

# A seed is only scannable if its dataset was BUILT on the pinned SHA.  META.json
# records it (stages.events.darksirens_sha), so this catches a seed that predates the
# guard or was generated by hand against the main checkout.
seed_sha_ok () {
  local D=$1
  python - "$D/META.json" "$DS_PIN_SHA" <<'PYEOF'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(1)
want = sys.argv[2]
got = d.get("darksirens_sha") or d.get("stages", {}).get("events", {}).get("darksirens_sha")
sys.exit(0 if got == want else 1)
PYEOF
}

ready () { local D=$DATA/seed$1
  for f in surveys/survey_gal_complete_ns32.h5 surveys/survey_agn_complete_ns32.h5 \
           events/events.h5 injections/injections_targeted.h5; do
    [ -s "$D/$f" ] || return 1; done
  seed_sha_ok "$D" || { echo "[a2] seed $1 built on the WRONG darksirens SHA; refusing" >&2; return 1; }
  return 0; }

DONE=0
while true; do
  CLAIM=""
  for i in $(seq 1 "$N"); do
    [ -d "$Q/claim_$i" ] && continue
    read -r SEED LANE CHUNK NCHUNK < <(sed -n "${i}p" "$Q/tasks.txt")
    ready "$SEED" || continue
    if mkdir "$Q/claim_$i" 2>/dev/null; then CLAIM=$i; break; fi
  done

  if [ -z "$CLAIM" ]; then
    OUTSTANDING=$(for i in $(seq 1 "$N"); do [ -d "$Q/claim_$i" ] || echo x; done | wc -l)
    if [ "$OUTSTANDING" -eq 0 ] || [ -f "$Q/STOP" ]; then
      echo "[a2 $ME] queue drained ($DONE chunks here); exiting"; break; fi
    echo "[a2 $ME] $(date -u +%T) $OUTSTANDING chunks waiting on generation; sleeping 300s"
    sleep 300; continue
  fi

  read -r SEED LANE CHUNK NCHUNK < <(sed -n "${CLAIM}p" "$Q/tasks.txt")
  echo "$ME $(date -u +%FT%TZ)" > "$Q/claim_$CLAIM/owner"
  SUF=""; [ "$LANE" = "popuni" ] && SUF="_popuni"
  TAG="joint_s${SEED}${SUF}_c${CHUNK}"
  if [ -f "$A2/results/chunks/${TAG}.h5" ]; then
    echo "[a2 $ME] $TAG already present; skipping"; touch "$Q/claim_$CLAIM/done"; continue; fi

  echo "[a2 $ME] $(date -u +%T) -> $TAG"
  T0=$(date +%s)
  if ( cd "$A2" && KIND=joint SEED=$SEED LANE=$LANE CHUNK=$CHUNK NCHUNK=$NCHUNK ./scripts/run_scan.sh ); then
    DT=$(( $(date +%s) - T0 )); DONE=$((DONE+1))
    touch "$Q/claim_$CLAIM/done"; echo "[a2 $ME] $TAG OK in ${DT}s"
  else
    DT=$(( $(date +%s) - T0 ))
    touch "$Q/claim_$CLAIM/failed"; echo "[a2 $ME] $TAG FAILED after ${DT}s"
  fi
done
echo "[a2 $ME] exit $(date -u +%FT%TZ)"
